[tasks.build-debug]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "webssh", "--out-dir", "./pkg", "--dev"]

[tasks.build-release]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "webssh", "--out-dir", "./pkg"]

[tasks.install-debug]
dependencies=["build-debug", "install_wasm", "install_html"]

[tasks.install-release]
dependencies=["build-release", "install_wasm", "install_html"]

[tasks.install_wasm]
script = '''
    mkdir -p $INSTALL_PATH
    cp ./pkg/webssh.js $INSTALL_PATH
    cp ./pkg/webssh_bg.wasm $INSTALL_PATH
    '''

[tasks.install_html]
script = '''
    cp assets/* $INSTALL_PATH
    '''