[tasks.build-debug]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./pkg", "--dev"]

[tasks.build-release]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./pkg"]

[tasks.install-debug]
dependencies=["build-debug", "install_wasm", "install_html"]

[tasks.install-release]
dependencies=["build-release", "install_wasm", "install_html"]

[tasks.install_wasm]
script = '''
    mkdir -p $FE_STATIC_INSTALL_PATH
    cp ./pkg/wasm.js $FE_STATIC_INSTALL_PATH
    cp ./pkg/wasm_bg.wasm $FE_STATIC_INSTALL_PATH
    '''

[tasks.install_html]
script = '''
    mkdir -p $FE_STATIC_INSTALL_PATH
    cp static/* $FE_STATIC_INSTALL_PATH
    '''

[env]
FE_STATIC_INSTALL_PATH="${INSTALL_PATH}/static"